# Generated by Django 3.2.3 on 2021-06-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tascasApp', '0003_tasca_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasca',
            name='tascaPicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
